#! /bin/bash
# ---------------------------------------------
# Author: gomesdigital, 09/10/2022
# Last Updated: 09/10/2022 
# ---------------------------------------------
# Installs communication programs.
# ---------------------------------------------

snap install slack --classic
snap install zoom-client

apt install discord
