#! /bin/bash
# ---------------------------------------
# Author: gomesdigital, 15/10/2022
# Last Modified: 15/10/2022
# ---------------------------------------
# Tools specific to containers.
# ---------------------------------------

# packages to allow apt to use repos over HTTPS
apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
# add GPG key
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
# intialize repo
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# install Docker engine
apt update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
