#! /bin/bash
# ---------------------------------------------
# Author: gomesdigital, 08/10/2022
# Last Updated: 08/10/2022 
# ---------------------------------------------
# Tools regarding databases.
# ---------------------------------------------

apt install mysql-client
