#! /bin/bash
# ---------------------------------------------
# Author: gomesdigital, 11/10/2022
# Last Updated: 11/10/2022 
# ---------------------------------------------
# Things yet to be classified.
# ---------------------------------------------

source ./config/env  # load user configurations

# nvm
# nvm is a shell function, not a binary
# ---> source it after install 
sudo -u "$USERNAME" bash -c "
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash;
source ~/.nvm/nvm.sh;
nvm install 16;
nvm install 18;
"

apt install awscli

npm install -g typescript

