#! /bin/bash
# ---------------------------------------------
# Author: gomesdigital, 11/10/2022
# Last Updated: 11/10/2022 
# ---------------------------------------------
# Things yet to be classified.
# ---------------------------------------------

source ./config/env  # load user configurations

# nvm
sudo -u "$USERNAME" bash -c "
git clone https://github.com/lukechilds/zsh-nvm /home/\"$USERNAME\"/.oh-my-zsh/custom/plugins/zsh-nvm;
sed -i '/^plugins=(git.*/a plugins+=(zsh-nvm)' /home/\"$USERNAME\"/.zshrc;
"

apt install awscli

npm install -g typescript

snap install spotify
