#! /bin/bash
# ---------------------------------------------
# Author: gomesdigital, 08/10/2022
# Last Updated: 08/10/2022 
# ---------------------------------------------
# Installs python modules only.
# ---------------------------------------------

# create default venv
mkdir ~/.venv
python3 -m venv ~/.venv/default

source ~/.venv/default/bin/activate
pip install requests
deactivate
